version: "3.3"
services:
  mongo-container:
    image: mongo
    container_name: mongo-container
    restart: on-failure
    environment:
      MONGO_INITDB_DATABASE: 'dev-mongo'
      MONGO_INITDB_ROOT_USERNAME: 'usr-mongo'
      MONGO_INITDB_ROOT_PASSWORD: 'pwd-mongo'
    ports:
      - 27016:27016
    expose:
      - 27016
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro